### ISSUE TITLE
Update news section

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#178]
we need to change the text from date and info, to reflect the event dates. If anyone has some inspiration for the text there, let's discuss over the ticket before we jump into the implementation

**Comment by claudmi** [comment]
We can start off with the text below, feel free to edit it if needed:

JSHeroes brings the latest and greatest on JavaScript and much more. Join us in April 2019 for 2 days of conference and 1 day of hands-on workshops.
JSHeroes 2019 will be held at Grand Hotel Italia, Strada Trifoiului 2, Cluj-Napoca, Romania.
To stay up-to-date, please follow us on [Twitter](https://twitter.com/jsheroes).

**Comment by alexnm** [comment]
ended up with this, tell me what you think about it

```Join us on the 11th and 12th of April 2019 for 2 days of conference, with a kick-off day full of workshops on the 10th. Feel free to send us your suggestions over Twitter, we’d be happy to hear from you.```

**Comment by claudmi** [comment]
What suggestions are you requesting, about talks, workshops, speakers? I edited that sentence.
Also added the info on the venue since the tab is called Date and Venue:

> Join us on the 11th and 12th of April 2019 for 2 days of conference, with a kick-off day full of workshops on the 10th.
Feel free to send us your suggestions for talks or workshop topics over [Twitter](https://twitter.com/jsheroes), we’d be happy to hear from you.
JSHeroes 2019 will be held at Grand Hotel Italia, Strada Trifoiului 2, Cluj-Napoca, Romania.

**Comment by alexnm** [comment]
I changed it to Date and Agenda, venue is not that relevant
