### ISSUE TITLE
Implement ServiceWorker for offline support during the conf

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#206]
Would be cool to have offline support for the agenda during the event, I added a manifest file so the app is pwa-ready :)

**Comment by ecris87** [comment]
Hey, @alexnm @jonattfin, i heard on facebook you were looking for opensource contributors for jsheroes.io. Since i wanted to learn more about service workers and i want to contribute more to OSS i took a shot at this issue yesterday. Noticed only today it's no longer unassigned :(
I opened a PR in case you haven't started working yet on this: https://github.com/jsheroes/jsheroes.io/pull/239
