### ISSUE TITLE
Add Continuous Code Quality with SonarQube

### ISSUE THREAD

**Issue by jonattfin** [jsheroes/jsheroes.io#288]
https://sonarcloud.io provides continuous code quality as a free tier, and I thought that JSHeroes website should benefit from it.

**Comment by jonattfin** [comment]
@danielmocan, @alexnm, @ecris87 What do you think?

**Comment by ecris87** [comment]
Good idea. I'm in favour of something like this.
I would like to suggest [Code Climate](https://codeclimate.com/) instead of SonarQube. 

Code Climate Pros:
* Has github integration, free for OSS
* After each Git push, Code Climate analyzes your code for complexity, duplication, and common smells
* Adds comments using a *bot* about those issues, for example:
<img width="749" alt="screen shot 2019-01-08 at 15 34 46" src="https://user-images.githubusercontent.com/5598081/50833765-faf73480-135a-11e9-99bd-8a2720ff535c.png">
<img width="756" alt="screen shot 2019-01-08 at 15 34 32" src="https://user-images.githubusercontent.com/5598081/50833772-fcc0f800-135a-11e9-9d22-0d0c7bb5d03f.png">
<img width="716" alt="screen shot 2019-01-08 at 15 36 11" src="https://user-images.githubusercontent.com/5598081/50834083-cafc6100-135b-11e9-8345-4059a2cf1bd3.png">

Code Climate Cons:
* Sometimes complains about small stylistic decisions

I confess i haven't worked with SonarQube, so i don't know how it will look like when integrated. I like that Code Climate has a bot that's added automatically as a reviewer and adds comments. 
Either solution would be ok for me.

**Comment by jonattfin** [comment]
@ecris87, sure no matter which one, the results are the same, better code quality :-) It's yours if you want to do it... / I have to fix some others bugs..

**Comment by danielmocan** [comment]
I did not work with any of them. 
The only down side of Code Climate is that it does not have any free tier.
It's not a problem with money, but we can properly test with the free tier SonarQube.

Maybe would be interesting to present this two options in a meetup, what do you think @jonattfin @ecris87 ?

**Comment by jonattfin** [comment]
let's try sonarqube then :-)

**Comment by ecris87** [comment]
@danielmocan Code climate is free for public github repos. But SonarQube is good too, looking forward to seeing it in action :)
Agree with @jonattfin's point abt code quality as a larger topic 👍
