### ISSUE TITLE
Prepare site for 2020

### ISSUE THREAD

**Issue by alexnm** [jsheroes/jsheroes.io#385]
A few changes needed on the website while preparing for 2020:
1. [ ] banner image should be updated (see #383)
2. [ ] new data folders need to be added for 2020 (no speakers, sponsors, partners, communities for now, I will fill that up later)
3. [ ] the aftermovie (https://www.youtube.com/watch?v=jdr9eQGq97g) should be added as an embed after the image, I think we already had the component from last year when we did something similar.
4. [ ] **mission** section should be hidden from the main page and removed from the menu for now
5. [ ] **schedule** should display: "coming soon" or can be removed like mission
6. [ ] **stats** section should be added with new numbers - @danielmocan can you help here?
7. [ ] two new rows of images should be added in the photos section - with the photos from 2019 and the videos from 2019 as links
8. [ ] a 2019 pages should be added and linked in the header, same layout as 2018

**Comment by claudmi** [comment]
Regarding this #item: 
two new rows of images should be added in the photos section - with the photos from 2019 and the videos from 2019 as links

I propose to have the photo gallery section always related to the previous edition, i.e. in this case have a photo gallery, and links to videos & photos from JSH 2019. The links to photos & videos from 2018 & 2017 can be included in the Highlights section of jsheroes.io/2018 and .../2017.
Does this sound ok? If so I'll create a mockup for the 2019 photo gallery section.

**Comment by jonattfin** [comment]
@danielmocan - i would like to take the data from the sites ... making api calls, do don't need to update them in the future/they will be updated.

**Comment by jonattfin** [comment]
@claudmi, i've added the photogallery item to antoher task: Prepare site for 2020 - photo gallery #386

**Comment by jonattfin** [comment]
hello all, i've reopened two new tasks for the photo gallery & the stats.

**Comment by claudmi** [comment]
Attached the 2019 photo gallery mockup -- it's done in illustrator, so cannot be exported to Zeplin, but it should be fine, since you only have to replace the photos and edit the text/links.
![photo-gallery-1920px-section](https://user-images.githubusercontent.com/210512/58839877-d9794b00-8663-11e9-862f-ccd79a335760.png)

The photos are here:
[jsh-photo-gallery-2019.zip](https://github.com/jsheroes/jsheroes.io/files/3249771/jsh-photo-gallery-2019.zip)

Links:
2019 Photos: 
https://www.facebook.com/pg/jsheroes/photos/?tab=album&album_id=2275719352665968

2019 Videos:
https://www.youtube.com/watch?v=jdr9eQGq97g&list=PLB9NqTp0uKrR8WFXitMvLMGd-kGGZ4RkX

2019 Website:
we need to create https://jsheroes.io/2019
